### ISSUE TITLE
Scrollbar damping

### ISSUE THREAD

**Issue by Youzid** [lucafanselau/jongleur#9]
we cannot  style or configure how the scroll bar behave , it would be great to have options  to change the speed of scroll bar or styles to hide it for example

**Comment by fanselau** [comment]
So actually there is not that much to do with scrollbar. You can redesign it, but that happens at a global level with CSS (something like https://codepen.io/devstreak/pen/dMYgeO). Damping is applied to the scroll controls already. The only thing that I think would be nice-to-have is a flag on the `Scroll.At` utility to let div's behave "as-if" the scrollbar would be damped)

For now I will close this issue, feel free to re-open if you have any additional input to this
